# Generated by Django 5.1.4 on 2025-01-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
