# Generated by Django 5.1.4 on 2025-01-10 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='viewed_by',
            field=models.ManyToManyField(related_name='viewed_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
